services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/src/app
      - /src/app/node_modules
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - REDIS_URL=${REDIS_URL}
      - BASE_URL=${BASE_URL}
    depends_on:
      - mongo
      - redis
    networks:
      - url-net
  
  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - url-net
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes --appendfsync everysec
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - url-net

volumes:
  mongo-data:
  redis-data:

networks:
  url-net:
    driver: bridge